# Site settings
title: Herramientas Ciudadanas
email: contacto@ciudadanointeligente.org
description: ""
baseurl: "//ciudadanointeligente.github.io/redeployment/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ciudadanoi

# Build settings
markdown: kramdown

analytics_id: 'UA-76464035-1'

collections:
  tools:
    output: true
